---
title: "Predicting Housing Prices with ARIMA models"
author: "Olumide Adewole"
date: "19/03/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Import Libraries
library(forecast)
library(tseries)
library(tidyverse)
```

```{r}
setwd("/Users/nolimitmide/Desktop/House Price Prediction with R")
```

```{r}
# importing our data
house_data <- read.csv("SPCS20RPSNSA.csv")

# Check data import
head(house_data)
```

```{r}
# Change name of data column to Units
names(house_data)[2] <- "Units"

# Creates a Units Object as intermediate to transform into time series
hd_units <- house_data$Units

# Creates Time Series Object that starts in January with a monthly frequency
thouse_data <- ts(hd_units,
  start = c(2000, 1),
  frequency = 12
)

# Check Data Transformation
thouse_data
```

```{r}
# Automatically create ARIMA model
fit <- auto.arima(thouse_data)
fit
```

```{r}
# Check Accuracy
accuracy(fit)
```

```{r}
# Create a Simple Plot with a forecast for the next year
plot(forecast(fit, 12),
  xlab = "Date",
  ylab = "Units",
  main = "ARIMA Forecast for Case-Shiller House Data"
)
```

```{r}
# Get table of forecasted values.
pred_values <- forecast(fit, 12)
pred_values
```

# Checking our assumptions

```{r}
# Check assumptions of normality & Autocorrelation
qqnorm(fit$residuals)
qqline(fit$residuals)
Box.test(fit$residuals, type = "Ljung-Box")
# Has high p-value, so autocorrelations not significantly different than 0
# There are a few possible outliers, but most of the data is normally distributed
```

```{r}
# Transform time series to log scale
lthouse_data <- log(thouse_data)
# check if it worked
head(lthouse_data)
```

```{r}
# Create new fit on log scale series for seasonal decomposition
fit2 <- stl(lthouse_data, s.window = "period")
# Plot Seasonal Decomposition
plot(fit2, main = "Seasonal Decomposition of log(Case-Shiller Units)")
```

```{r}
# Create a Season Plot
ggseasonplot(thouse_data, year.labels = TRUE, col = rainbow(20))
```

```{r}
# Automatically create ARIMA model
fit3 <- auto.arima(lthouse_data)
fit3
```

# second model accuracy checking

```{r}
# Check Accuracy
fit_accuracy <- data.frame(accuracy(fit))
fit_accuracy2 <- data.frame(accuracy(fit3))
final_fit_accuracy <- rbind(fit_accuracy, fit_accuracy2)
final_fit_accuracy
```

```{r}
# Create a Simple Plot with a logged forecast for the next year
plot(forecast(fit3, 12),
  xlab = "Date",
  ylab = "Units",
  main = "ARIMA Forecast for Case-Shiller Hpuse Data"
)
```

```{r}
# Get table of forecasted values.

# Original Data
pred_values <- data.frame(forecast(fit, 12))

# Log transformed data
pred_values2 <- data.frame(forecast(fit3, 12))
pred_values2[, 1:5] <- exp(pred_values2[, 1:5])

# Merge forecast predictions!
merged_df <- data.frame(
  Date = rownames(pred_values),
  Original_Data_Forecast = pred_values$Point.Forecast,
  Log_Transformed_Data_Forecast = pred_values2$Point.Forecast,
  Difference = round(pred_values$Point.Forecast - pred_values2$Point.Forecast, 2) #nolint
)
merged_df
```